// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rizmmcyopthgfmdzsrxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpem1tY3lvcHRoZ2ZtZHpzcnhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUzMTUzMzAsImV4cCI6MjA1MDg5MTMzMH0.XZ1YuLR-tofWMSC79Vf-D61gPS13dwJxC4WPZmseDOA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);